account/urls.py
from django.urls import path
from .views import *

urlpatterns = [
  path('login/', login_view, name = "login"),
  path('logout/', logout_view, name = "logout"),
  path('register/',register_view, name = "signup"),
]

main/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', home, name="home"),
    path('musical/<pID>', musical_detail, name="musical"),
    path('musical/like/<pID>', like_product, name="like_product"),
    path('community/<str:id>', detail, name="detail"),
    path('community/', community, name="community"),
    path('community/create/', create, name="create"),
    path('mypage/', mypage, name="mypage"),
    path('musical_list/', musical_list, name="musical_list"),
    path('modify/<str:id>', modify, name="modify"),
    path('delete/<str:id>', delete, name="delete"),
    path('post/scrap/<str:id>', post_scrap, name="post_scrap")
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('account/', include('account.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    
    nickname = models.CharField(verbose_name='닉네임', max_length=100, default='')
   
    def __str__(self):
        return self.nickname

account/forms.py
from django import forms
from .models import CustomUser
from django.contrib.auth.forms import UserCreationForm

class UserForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = '__all__'

class RegisterForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'password1', 'password2', 'nickname']

account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import authenticate, login, logout
from .forms import RegisterForm

def login_view(request):
  if request.method == 'POST':
    form = AuthenticationForm(request=request, data=request.POST)
    if form.is_valid():
      username = form.cleaned_data.get("username")
      password = form.cleaned_data.get("password")
      user = authenticate(request=request, username=username, password=password)
      if user is not None:
        login(request, user)
        return redirect("home")
    else:
      form = AuthenticationForm()
      ctx = {
        'form': form,
        'error': '가입하지 않은 아이디이거나, 잘못된 비밀번호입니다.'
      }
      return render(request, "login.html", ctx)

  else:
    form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})


def logout_view(request):
  logout(request)
  return redirect("home")

def register_view(request):
  if request.method == "POST":
    form = RegisterForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('home')

    else:
      form = RegisterForm()
      ctx = {
        'form': form,
        'error': '회원가입 형식에 맞게 입력해주세요.'
      }
      return render(request, 'signup.html', ctx)

  else:
    form = RegisterForm()
    return render(request, 'signup.html', {'form':form})

account/templates/login.html
{% extends 'base.html' %}
{% block content %}

{% load static %}


<style>
  
  .container {
    margin-left: auto;
    margin-right: auto;
  }

  h2 {
    text-align: center;
  }

  form {
    text-align: center;
  }
  
  button {
        background: #4b0057; 
        border-radius: 20px; 
        color: white;
        border: none;
        height: 30px;
        cursor: pointer;
        padding-left: 20px;
        padding-right: 20px;
  }

  a {
    color: black;
  }

  a:visited {
    color: black;
  }
  
  a:link {
    color: black;
    text-decoration: none;
  }

  a:hover{
    color: #4b0057;
  }

  .error{
    text-align: center;
    color: red;
  }

  nav {
    width: 100%;
    height: 10%;
  }

  input {
    border-radius: 15px;
    width: 300px;
    height: 35px;
    border-color: #4b0057;
    transition: background-color 0.2s ease-in-out;
  }

  input:focus {
    background-color: #4b0057;
    color: white;
  }
    
  .account {
    background-color: #f2f2f2;
  }

  .input_id, .input_pw {
    width: 65%;
    display: flex;
    justify-content: left;
  }

  .label_id, .label_pw {
    width: 35%;
    text-align: right;
  }
      
</style>

<body>


<!-- 기존 로그인 form

  <div class="container">
    <br>
    <h2>로그인</h2>
    <br>
    {% if error %} <p class="error">{{error}}</p> {% endif %}
    <form action="{% url 'login' %}" method="post" class="login_info">
      {%csrf_token%}
      <h4>아이디 <input name="username" type="text" class="account"></h4>
      <h4>비밀번호 <input name="password" type="password" class="account"></h4>
      <br><button type="submit">LOGIN</button>
      <br>
      <br>
      <a href="{% url 'signup' %}">
        <p>아직 계정이 없으신가요?</p>
      </a>
    </form>
  </div>

-->


<div class="container">
  <br>
  <h2>로그인</h2>
  <br>
  {% if error %} <p class="error">{{error}}</p> {% endif %}
  <form action="{% url 'login' %}" method="post" class="login_info">
      {%csrf_token%}
    <div class="container_my-3">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td class="label_id">아이디</td>
            <td class="input_id"><input name="username" type="text" class="account"></td>
          </tr>
          <tr>
            <td class="label_pw">비밀번호</td>
            <td class="input_pw"><input name="password" type="password" class="account"></td>
          </tr>
        </tbody>
      </table>
      <br>
      <button type="submit">LOGIN</button>
      <br>
      <br>
      <br>
      <a href="{% url 'signup' %}"><p>아직 계정이 없으신가요?</p></a>
    </div>
  </form>
</div>


</body>

{% endblock %}

account/templates/signup.html
{% extends 'base.html' %}
{% block content %}

<style>

  .container {
    margin-left: auto;
    margin-right: auto;
  }

  h2 {
    margin: 20;
    text-align: center;
  }

  form {
    margin: 20;
    text-align: center;
  }

  button {
    background: #4b0057; 
    border-radius: 20px; 
    color: white;
    border: none;
    height: 30px;
    cursor: pointer;
    padding-left: 20px;
    padding-right: 20px;
  }

  .error{
    text-align: center;
    color: red;
  }

  p1 {
    font-size: 11px;
    display:block;
    font-weight: bold;
    color: rgb(102, 43, 89)
  }

  nav {
    width: 100%;
    height: 10%;
  }

  input {
    border-radius: 15px;
    width: 250px;
    height: 35px;
    border-color: #4b0057;
    transition: background-color 0.2s ease-in-out;
  }

  input:focus {
    background-color: #4b0057;
    color: white;
  }

  .input_id, .input_nn, .input_pw, .input_check {
    width: 63%;
    display: flex;
    justify-content: left;
  }

  .label_id, .label_nn, .label_pw, .label_check {
    width: 37%;
    text-align: right;
  }

</style>

<body>

<!-- 기존 회원가입 form

  <div class="container">
    <br>
    <h2>회원가입</h2>
    <br>
    {% if error %} <p class="error">{{error}}</p> {% endif %}
    <form method="POST">
      {% csrf_token %}
      <h4>아이디 <input name="username" type="text"></h4>

      <h4><label for="id_nickname">닉네임</label>
        <input type="text" name="nickname" maxlength="100" required id="id_nickname"></h4>

      <h4>비밀번호 <input name="password1" type="password"></h4>
      <h4>비밀번호 확인 <input name="password2" type="password"></h4>
      <p1>비밀번호는 최소 8 문자 이상으로 구성해주세요.</p1>
      <p1>최소 숫자와 문자를 포함해주세요.</p1><br>
      <br><button type="submit">회원 등록</button>
    </form>
  </div>
-->

<div class="container">
  <br>
  <h2>회원가입</h2>
  <br>
  {% if error %} <p class="error">{{error}}</p> {% endif %}
  <form method="POST">
    {%csrf_token%}
    <div class="container_my-3">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td class="label_id">아이디</td>
            <td class="input_id"><input name="username" type="text"></td>
          </tr>
          <tr>
            <td class="label_nn">닉네임</td>
            <td class="input_nn"><input type="text" name="nickname" maxlength="100" required id="id_nickname"></td>
          </tr>
          <tr>
            <td class="label_pw">비밀번호</td>
            <td class="input_pw"><input name="password1" type="password"></td>
          </tr>
          <tr>
            <td class="label_check">비밀번호 확인</td>
            <td class="input_check"><input name="password2" type="password"></td>
          </tr>
        </tbody>
      </table>
      <br>
      <p1>비밀번호는 최소 8 문자 이상으로 구성해주세요.</p1>
      <p1>최소 숫자와 문자를 포함해주세요.</p1><br>
      <br>
      <button type="submit">회원 등록</button>
    </div>
  </form>
</div>


</body>

{% endblock %}